# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
#use_frameworks!

target 'money' do
    #定义dayibase的版本。
pod 'Reveal-iOS-SDK' ,:configurations => ['Debug']
#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
pod 'JPush'
end


